version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "rmuser"
      RABBITMQ_DEFAULT_PASS: "rmpassword"
    ports:
      - "15672:15672"
      - "5672:5672"

  minio:
    image: docker.io/bitnami/minio:2025
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_DEFAULT_BUCKETS: "bucket"
    volumes:
      - 'minio_data:/bitnami/minio/data'

volumes:
    minio_data:
      driver: local